### ISSUE TITLE
FPS value does not go up to the specified FPS value when watching live.

### ISSUE THREAD

**Issue by reindex-ot** [Kimjio/umamusume-localify-android#21]
It runs at 120 FPS in menus and stories, but drops to around 60 FPS when live.

**Comment by Kimjio** [comment]
I think the drop is due to device performance issues or high graphics settings.
It can also drop further depending on the complexity of the live stage.


![Screenshot_20230422-115553_ウマ娘](https://user-images.githubusercontent.com/10695980/233758955-127a15db-64c2-49e7-b23c-fbbeab0b1bda.png)
When I played on my OnePlus 7 Pro, I didn't have any issues as you can see in the screenshot.

**Comment by reindex-ot** [comment]
Is it possible to depend on the contents of the asset, the settings, and the device? I see... By the way, I'd like to contact you outside of here, like on Discord or something.
